// ProjectCardStyles.js

const projectCardStyles = {
  parent: {
    width: "290px",
    height: "300px",
    perspective: "1000px",
  },
  card: {
    height: "100%",
    borderRadius: "50px",
    background:
      "linear-gradient(135deg, rgb(0, 255, 214) 0%, rgb(8, 226, 96) 100%)",
    transition: "all 0.5s ease-in-out",
    transformStyle: "preserve-3d",
    boxShadow:
      "rgba(5, 71, 17, 0) 40px 50px 25px -40px, rgba(5, 71, 17, 0.2) 0px 25px 25px -5px",
  },
  glass: {
    transformStyle: "preserve-3d",
    position: "absolute",
    inset: "8px",
    borderRadius: "55px",
    borderTopRightRadius: "100%",
    background:
      "linear-gradient(0deg, rgba(255, 255, 255, 0.349) 0%, rgba(255, 255, 255, 0.815) 100%)",
    transform: "translate3d(0px, 0px, 25px)",
    borderLeft: "1px solid white",
    borderBottom: "1px solid white",
    transition: "all 0.5s ease-in-out",
  },
  content: {
    padding: "100px 60px 0px 30px",
    transform: "translate3d(0, 0, 26px)",
  },
  title: {
    display: "block",
    color: "#00894d",
    fontWeight: "900",
    fontSize: "20px",
  },
  text: {
    display: "block",
    color: "rgba(0, 137, 78, 0.7647058824)",
    fontSize: "15px",
    marginTop: "20px",
  },
  bottom: {
    padding: "10px 12px",
    transformStyle: "preserve-3d",
    position: "absolute",
    bottom: "20px",
    left: "20px",
    right: "20px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    transform: "translate3d(0, 0, 26px)",
  },
  viewMore: {
    display: "flex",
    alignItems: "center",
    width: "40%",
    justifyContent: "flex-end",
    transition: "all 0.2s ease-in-out",
  },
  viewMoreButton: {
    background: "none",
    border: "none",
    color: "#00c37b",
    fontWeight: "bolder",
    fontSize: "12px",
  },
  viewMoreSvg: {
    fill: "none",
    stroke: "#00c37b",
    strokeWidth: "3px",
    maxHeight: "15px",
  },
  socialButtonsContainer: {
    display: "flex",
    gap: "10px",
    transformStyle: "preserve-3d",
  },
  socialButton: {
    width: "30px",
    aspectRatio: "1",
    padding: "5px",
    background: "rgb(255, 255, 255)",
    borderRadius: "50%",
    border: "none",
    display: "grid",
    placeContent: "center",
    boxShadow: "rgba(5, 71, 17, 0.5) 0px 7px 5px -5px",
  },
  logo: {
    position: "absolute",
    right: "0",
    top: "0",
    transformStyle: "preserve-3d",
  },
  circle: {
    display: "block",
    position: "absolute",
    aspectRatio: "1",
    borderRadius: "50%",
    top: "0",
    right: "0",
    boxShadow: "rgba(100, 100, 111, 0.2) -10px 10px 20px 0px",
    WebkitBackdropFilter: "blur(5px)",
    backdropFilter: "blur(5px)",
    background: "rgba(0, 249, 203, 0.2)",
    transition: "all 0.5s ease-in-out",
  },
  circle1: {
    width: "170px",
    transform: "translate3d(0, 0, 20px)",
    top: "8px",
    right: "8px",
  },
  circle2: {
    width: "140px",
    transform: "translate3d(0, 0, 40px)",
    top: "10px",
    right: "10px",
    WebkitBackdropFilter: "blur(1px)",
    backdropFilter: "blur(1px)",
    transitionDelay: "0.4s",
  },
  circle3: {
    width: "110px",
    transform: "translate3d(0, 0, 60px)",
    top: "17px",
    right: "17px",
    transitionDelay: "0.8s",
  },
  circle4: {
    width: "80px",
    transform: "translate3d(0, 0, 80px)",
    top: "23px",
    right: "23px",
    transitionDelay: "1.2s",
  },
  circle5: {
    width: "50px",
    transform: "translate3d(0, 0, 100px)",
    top: "30px",
    right: "30px",
    display: "grid",
    placeContent: "center",
    transitionDelay: "1.6s",
  },
  circle5Svg: {
    width: "20px",
    fill: "white",
  },
};

export { projectCardStyles };
